[Greeter]
background=/usr/share/backgrounds/wallpaper-bladerunner2049.png
theme-name=Graphite-orange
icon-theme-name=Adwaita
font-name=DejaVu Sans 14
draw-user-backgrounds=false
draw-grid=false
show-hostname=true
show-power=true
show-keyboard=true
enable-hidpi=auto
